name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get timestamp
      id: timestamp
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          axute/omada-keycloak-authrelay:stable
          axute/omada-keycloak-authrelay:latest
          axute/omada-keycloak-authrelay:${{ steps.timestamp.outputs.date }}
