name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get timestamp
      id: timestamp
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:stable
          ghcr.io/${{ github.repository }}:${{ steps.timestamp.outputs.date }}
        labels: |
          org.opencontainers.image.title=${{ github.repository }}
          org.opencontainers.image.description=CI-built image from ${{ github.repository }}
          org.opencontainers.image.version=${{ steps.timestamp.outputs.date }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          maintainer=axute
